name: CI/CD Workflow

on:
  push:
    branches:
      - main  # Запускать при пуше в главную ветку
  pull_request:
    branches:
      - main  # Запускать при pull request в главную ветку

jobs:
  build:
    runs-on: ubuntu-latest  # Выбор операционной системы для CI (например, Ubuntu)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Клонирование репозитория

    - name: Install JDK 17 (Corretto)
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'  # Используем Amazon Corretto JDK
        java-version: '17'  # Установка JDK 17
        cache: 'maven'  # Кеширование зависимостей Maven
        
    # Установка зависимостей для Java (Maven)
    - name: Install dependencies (для Java)
      run: |
        mvn install  # Для Maven-проекта на Java
    # Запуск Java тестов
    - name: Run Java tests
      run: mvn test  # Запуск Java тестов


    # Установка Newman для выполнения Postman коллекций
    - name: Install Newman
      run: |
        npm install -g newman  # Установка Newman's CLI для выполнения Postman коллекций
    # Запуск Postman тестов
    - name: Run Postman tests
      run: |
        newman run ./src/postman/collections/Login_Collection.postman_collection.json || echo "Postman collection not found"
        newman run ./src/postman/collections/Product_Collection.postman_collection.json || echo "Postman collection not found"
        newman run ./src/postman/collections/Home_Collection.postman_collection.json || echo "Postman collection not found"
