name: CI/CD Workflow

on:
  push:
    branches:
      - main  # Запускать при пуше в главную ветку
  pull_request:
    branches:
      - main  # Запускать при pull request в главную ветку

jobs:
  build:
    runs-on: ubuntu-latest  # Выбор операционной системы для CI (например, Ubuntu)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Клонирование репозитория

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Установка Python 3.9

    - name: Install dependencies (для Python)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Установка зависимостей для Python

    - name: Run Python tests
      run: |
        pytest  # Запуск Python тестов

    - name: Run Postman tests
      run: |
        npm install -g newman  # Установка Newman's CLI для выполнения Postman коллекций
        newman run ./src/postman/collections/login_collection.json  # Запуск коллекции тестов из Postman
        newman run ./src/postman/collections/product_collection.json
        newman run ./src/postman/collections/home_collection.json
