name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install JDK 17 (Corretto)
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'
        cache: 'maven'

    - name: Clean and install dependencies
      run: |
        mvn clean install -DskipTests
        
    - name: Install ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver


    - name: Run Java tests
      run: mvn test

    # - name: Set up Python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.9'

    # - name: Install dependencies (для Python)
    #   run: |
    #     python -m pip install --upgrade pip
    #     if [ -f "requirements.txt" ]; then
    #       pip install -r requirements.txt
    #     else
    #       echo "requirements.txt not found"
    #     fi

    # - name: Run Python tests
    #   run: |
    #     if [ -d "src/python_tests/tests" ]; then
    #       pytest src/python_tests/tests
    #     else
    #       echo "No Python tests found, skipping..."
    #     fi
    #   continue-on-error: true

    - name: Install Newman
      run: |
        npm install -g newman

    - name: Run Postman tests
      run: |
        if [ -f "./src/postman/collections/Login_Collection.postman_collection.json" ]; then
          newman run ./src/postman/collections/Login_Collection.postman_collection.json
        else
          echo "Login collection not found"
        fi
        if [ -f "./src/postman/collections/Product_Collection.postman_collection.json" ]; then
          newman run ./src/postman/collections/Product_Collection.postman_collection.json
        else
          echo "Product collection not found"
        fi
        if [ -f "./src/postman/collections/Home_Collection.postman_collection.json" ]; then
          newman run ./src/postman/collections/Home_Collection.postman_collection.json
        else
          echo "Home collection not found"
        fi

    # - name: Generate Allure report
    #   run: |
    #     mvn allure:report

    # - name: Upload Allure report as artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: allure-report
    #     path: target/site/allure-maven-plugin
