name: CI/CD Workflow

on:
  push:
    branches:
      - main  # Запускать при пуше в главную ветку
  pull_request:
    branches:
      - main  # Запускать при pull request в главную ветку

jobs:
  build:
    runs-on: ubuntu-latest  # Выбор операционной системы для CI (например, Ubuntu)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Клонирование репозитория

    - name: Install JDK 17 (Corretto)
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'  # Используем Amazon Corretto JDK
        java-version: '17'  # Установка JDK 17
        cache: 'maven'  # Кеширование зависимостей Maven
        
    # Установка зависимостей для Java (Maven)
    - name: Install dependencies (для Java)
      run: |
        mvn install  # Для Maven-проекта на Java

    # Запуск Java тестов
    - name: Run Java tests
      run: mvn test  # Запуск Java тестов

    # Установка Python 3.9
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Установка Python 3.9

    # Установка зависимостей для Python
    - name: Install dependencies (для Python)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Установка зависимостей для Python

    # Запуск Python тестов
    - name: Run Python tests
      run: |
        pytest src/python_tests/tests || echo "No tests found, skipping..."
      continue-on-error: true  # Это позволяет продолжить выполнение даже если тесты не найдены

    # Установка Newman для выполнения Postman коллекций
    - name: Install Newman
      run: |
        npm install -g newman  # Установка Newman's CLI для выполнения Postman коллекций

    # Запуск Postman тестов
    - name: Run Postman tests
      run: |
        newman run ./src/postman/collections/Login_Collection.postman_collection.json || echo "Postman collection not found"
        newman run ./src/postman/collections/Product_Collection.postman_collection.json || echo "Postman collection not found"
        newman run ./src/postman/collections/Home_Collection.postman_collection.json || echo "Postman collection not found"

#    - name: Generate Allure report
#      run: |
#        mvn allure:report
#
#    - name: Upload Allure report as artifact
#      uses: actions/upload-artifact@v4
#      with:
#        name: allure-report
#        path: reports/allure_reports






