name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install JDK 17 (Corretto)
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'

      - name: Run Java tests
        run: mvn clean test

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Login Collection
        run: |
          newman run ./src/postman/collections/Login_Collection.postman_collection.json \
            --environment ./src/postman/environments/Local\ Environment.postman_environment.json || echo "Login Collection failed"

      - name: Run Postman Product Collection
        run: |
          newman run ./src/postman/collections/Product_Collection.postman_collection.json \
            --environment ./src/postman/environments/Local\ Environment.postman_environment.json || echo "Product Collection failed"

      - name: Run Postman Home Collection
        run: |
          newman run ./src/postman/collections/Home_Collection.postman_collection.json \
            --environment ./src/postman/environments/Local\ Environment.postman_environment.json || echo "Home Collection failed"
